import { Customer, Invoice, Payment, LedgerEntry, CollectionTask, CollectionAttempt, PromiseToPay, Organization, User } from '../../src/types/index.js';

export const DEMO_ORG: Organization = {
  id: 'org-algeria-dist-01',
  name: 'مؤسسة التوزيع السريع الجزائر',
  tradeName: 'SARL DISTRIBU-ALGER',
  businessType: 'توزيع المواد الغذائية والاستهلاكية بالجملة',
  wilaya: 'الجزائر العاصمة',
  commune: 'براقي',
  phone: '0560 12 34 56',
  currency: 'DZD',
  plan: 'business',
};

export const DEMO_USERS: User[] = [
  {
    id: 'user-demo',
    name: 'أمين بن علي (المدير العام)',
    email: 'demo@mizan.dz',
    phone: '0550 11 22 33',
    role: 'owner',
    organizationId: 'org-algeria-dist-01',
  },
  {
    id: 'user-01',
    name: 'أمين بن علي',
    email: 'amine@distri-alger.dz',
    phone: '0550 11 22 33',
    role: 'owner',
    organizationId: 'org-algeria-dist-01',
  },
  {
    id: 'user-02',
    name: 'سمير قادري',
    email: 'samir.k@distri-alger.dz',
    phone: '0661 44 55 66',
    role: 'manager',
    organizationId: 'org-algeria-dist-01',
  },
  {
    id: 'user-03',
    name: 'كريم براهيمي',
    email: 'karim.b@distri-alger.dz',
    phone: '0770 88 99 00',
    role: 'collector',
    organizationId: 'org-algeria-dist-01',
  },
];

export function generateInitialAlgerianData() {
  const orgId = DEMO_ORG.id;
  const now = new Date();

  const daysAgo = (days: number) => {
    const d = new Date(now);
    d.setDate(d.getDate() - days);
    return d.toISOString().split('T')[0];
  };

  const daysAhead = (days: number) => {
    const d = new Date(now);
    d.setDate(d.getDate() + days);
    return d.toISOString().split('T')[0];
  };

  const customers: Customer[] = [
    {
      id: 'cust-01',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-001',
      name: 'محمد بلقاسم',
      companyName: 'سوبرماركت البركة والتوفيق',
      phone: '0550 45 89 12',
      whatsapp: '0550 45 89 12',
      address: 'حي البدر - شارع فلسطين',
      wilaya: 'الجزائر العاصمة',
      commune: 'القبة',
      customerType: 'retailer',
      creditLimit: 600000,
      paymentTermsDays: 30,
      totalInvoiced: 850000,
      totalPaid: 450000,
      outstandingBalance: 400000,
      overdueBalance: 280000,
      oldestDueDate: daysAgo(35),
      lastPaymentDate: daysAgo(40),
      riskScore: 78,
      riskLevel: 'high',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'عميل قديم، لديه مشكلة سيولة مؤقتة، يحتاج متابعة حثيثة',
      createdAt: daysAgo(120),
      updatedAt: daysAgo(2),
    },
    {
      id: 'cust-02',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-002',
      name: 'عبد القادر معوش',
      companyName: 'مؤسسة معوش لمواد البناء والتجهيز',
      phone: '0661 78 23 45',
      whatsapp: '0661 78 23 45',
      address: 'المنطقة الصناعية سيدي إبراهيم',
      wilaya: 'سيدي بلعباس',
      commune: 'سيدي بلعباس',
      customerType: 'wholesaler',
      creditLimit: 1200000,
      paymentTermsDays: 45,
      totalInvoiced: 1450000,
      totalPaid: 900000,
      outstandingBalance: 550000,
      overdueBalance: 550000,
      oldestDueDate: daysAgo(48),
      lastPaymentDate: daysAgo(60),
      riskScore: 84,
      riskLevel: 'critical',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'تجاوز مهلة السداد عدة مرات، سجل وعد دفع ولم ينفذه',
      createdAt: daysAgo(180),
      updatedAt: daysAgo(1),
    },
    {
      id: 'cust-03',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-003',
      name: 'ياسين حماني',
      companyName: 'مكتبة ومستلزمات الهضاب',
      phone: '0770 12 90 34',
      whatsapp: '0770 12 90 34',
      address: 'شارع 8 ماي 1945',
      wilaya: 'سطيف',
      commune: 'العلمة',
      customerType: 'retailer',
      creditLimit: 300000,
      paymentTermsDays: 30,
      totalInvoiced: 420000,
      totalPaid: 360000,
      outstandingBalance: 600000,
      overdueBalance: 60000,
      oldestDueDate: daysAgo(5),
      lastPaymentDate: daysAgo(15),
      riskScore: 28,
      riskLevel: 'low',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'زبون منضبط عموماً، تأخير خفيف فقط',
      createdAt: daysAgo(90),
      updatedAt: daysAgo(5),
    },
    {
      id: 'cust-04',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-004',
      name: 'هشام طاهري',
      companyName: 'طاهري إلكترونيكس وسيليكوم',
      phone: '0555 98 43 21',
      whatsapp: '0555 98 43 21',
      address: 'طريق الميناء',
      wilaya: 'وهران',
      commune: 'وهران',
      customerType: 'wholesaler',
      creditLimit: 800000,
      paymentTermsDays: 30,
      totalInvoiced: 1100000,
      totalPaid: 750000,
      outstandingBalance: 350000,
      overdueBalance: 190000,
      oldestDueDate: daysAgo(18),
      lastPaymentDate: daysAgo(25),
      riskScore: 54,
      riskLevel: 'medium',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'يسدد عبر CCP أو بريدي موب بانتظام نسبي',
      createdAt: daysAgo(150),
      updatedAt: daysAgo(3),
    },
    {
      id: 'cust-05',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-005',
      name: 'بشير عثماني',
      companyName: 'محلات الأوراس للمواد الغذائية',
      phone: '0662 33 11 88',
      whatsapp: '0662 33 11 88',
      address: 'حي كشيدة',
      wilaya: 'باتنة',
      commune: 'باتنة',
      customerType: 'retailer',
      creditLimit: 400000,
      paymentTermsDays: 15,
      totalInvoiced: 620000,
      totalPaid: 440000,
      outstandingBalance: 180000,
      overdueBalance: 180000,
      oldestDueDate: daysAgo(27),
      lastPaymentDate: daysAgo(32),
      riskScore: 72,
      riskLevel: 'high',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'متأخر 27 يوماً، يحتاج تذكيراً هاتفياً وتثبيت وعد بالدفع',
      createdAt: daysAgo(75),
      updatedAt: daysAgo(1),
    },
    {
      id: 'cust-06',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-006',
      name: 'رضا زرقين',
      companyName: 'صيدلية ومستحضرات النسيم',
      phone: '0772 44 66 88',
      whatsapp: '0772 44 66 88',
      address: 'وسط المدينة',
      wilaya: 'البليدة',
      commune: 'بوفاريك',
      customerType: 'retailer',
      creditLimit: 500000,
      paymentTermsDays: 30,
      totalInvoiced: 780000,
      totalPaid: 700000,
      outstandingBalance: 80000,
      overdueBalance: 0,
      oldestDueDate: daysAhead(10),
      lastPaymentDate: daysAgo(10),
      riskScore: 15,
      riskLevel: 'low',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'سداد ممتاز ومواعيد محترمة دائماً',
      createdAt: daysAgo(200),
      updatedAt: daysAgo(10),
    },
    {
      id: 'cust-07',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-007',
      name: 'فوزي دراجي',
      companyName: 'مؤسسة سيرتا للتجهيزات العامة',
      phone: '0561 22 77 99',
      whatsapp: '0561 22 77 99',
      address: 'المنطقة الحرفية زواغي سليمان',
      wilaya: 'قسنطينة',
      commune: 'قسنطينة',
      customerType: 'company',
      creditLimit: 1500000,
      paymentTermsDays: 60,
      totalInvoiced: 2100000,
      totalPaid: 1300000,
      outstandingBalance: 800000,
      overdueBalance: 450000,
      oldestDueDate: daysAgo(22),
      lastPaymentDate: daysAgo(45),
      riskScore: 68,
      riskLevel: 'high',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'يسدد بشيكات تجارية، يحتاج متابعة قبل إيداع الشيكات',
      createdAt: daysAgo(220),
      updatedAt: daysAgo(4),
    },
    {
      id: 'cust-08',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-008',
      name: 'كمال بلعيد',
      companyName: 'مؤسسة يوسف وبناته للمواد المنزلية',
      phone: '0660 55 12 34',
      whatsapp: '0660 55 12 34',
      address: 'شارع عبان رمضان',
      wilaya: 'بجاية',
      commune: 'أقبو',
      customerType: 'wholesaler',
      creditLimit: 700000,
      paymentTermsDays: 30,
      totalInvoiced: 930000,
      totalPaid: 650000,
      outstandingBalance: 280000,
      overdueBalance: 120000,
      oldestDueDate: daysAgo(12),
      lastPaymentDate: daysAgo(20),
      riskScore: 48,
      riskLevel: 'medium',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'تاجر نشط في منطقة وادي الصومام',
      createdAt: daysAgo(110),
      updatedAt: daysAgo(6),
    },
    {
      id: 'cust-09',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-009',
      name: 'علي شريف',
      companyName: 'محلات شريف للعطور ومواد التجميل',
      phone: '0770 99 44 22',
      whatsapp: '0770 99 44 22',
      address: 'حي الدرب',
      wilaya: 'تلمسان',
      commune: 'مغنية',
      customerType: 'retailer',
      creditLimit: 350000,
      paymentTermsDays: 20,
      totalInvoiced: 480000,
      totalPaid: 260000,
      outstandingBalance: 220000,
      overdueBalance: 220000,
      oldestDueDate: daysAgo(42),
      lastPaymentDate: daysAgo(50),
      riskScore: 82,
      riskLevel: 'critical',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'تأخر مستمر، لم يرد على آخر محاولة تواصل',
      createdAt: daysAgo(95),
      updatedAt: daysAgo(2),
    },
    {
      id: 'cust-10',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-010',
      name: 'عمر لخضاري',
      companyName: 'لخضاري للتغذية والتموين',
      phone: '0552 11 44 77',
      whatsapp: '0552 11 44 77',
      address: 'السوق المركزي',
      wilaya: 'عنابة',
      commune: 'عنابة',
      customerType: 'retailer',
      creditLimit: 500000,
      paymentTermsDays: 30,
      totalInvoiced: 610000,
      totalPaid: 490000,
      outstandingBalance: 120000,
      overdueBalance: 0,
      oldestDueDate: daysAhead(14),
      lastPaymentDate: daysAgo(8),
      riskScore: 20,
      riskLevel: 'low',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'عميل ممتاز، الدفع نقداً عند التوصيل أو خلال أسبوع',
      createdAt: daysAgo(140),
      updatedAt: daysAgo(8),
    },
    {
      id: 'cust-11',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-011',
      name: 'سليمان قرفي',
      companyName: 'قرفي لمواد التغليف والتوزيع',
      phone: '0663 88 12 90',
      whatsapp: '0663 88 12 90',
      address: 'المنطقة الحضرية الجديدة',
      wilaya: 'برج بوعريريج',
      commune: 'برج بوعريريج',
      customerType: 'distributor',
      creditLimit: 1000000,
      paymentTermsDays: 30,
      totalInvoiced: 1300000,
      totalPaid: 950000,
      outstandingBalance: 350000,
      overdueBalance: 150000,
      oldestDueDate: daysAgo(16),
      lastPaymentDate: daysAgo(28),
      riskScore: 50,
      riskLevel: 'medium',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'دفعات دورية عبر بريدي موب',
      createdAt: daysAgo(160),
      updatedAt: daysAgo(7),
    },
    {
      id: 'cust-12',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-012',
      name: 'عبد الحق غانم',
      companyName: 'سوبرماركت غانم إخوان',
      phone: '0771 66 33 22',
      whatsapp: '0771 66 33 22',
      address: 'طريق الأغواط',
      wilaya: 'الجلفة',
      commune: 'الجلفة',
      customerType: 'retailer',
      creditLimit: 450000,
      paymentTermsDays: 20,
      totalInvoiced: 580000,
      totalPaid: 320000,
      outstandingBalance: 260000,
      overdueBalance: 260000,
      oldestDueDate: daysAgo(38),
      lastPaymentDate: daysAgo(45),
      riskScore: 76,
      riskLevel: 'high',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'أعطى وعداً بالسداد ولم يتمكن، طلب مهلة إضافية',
      createdAt: daysAgo(130),
      updatedAt: daysAgo(3),
    },
    {
      id: 'cust-13',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-013',
      name: 'جمال بوحفص',
      companyName: 'واحة الجنوب للتجارة العامة',
      phone: '0554 77 00 11',
      whatsapp: '0554 77 00 11',
      address: 'شارع الاستقلال',
      wilaya: 'ورقلة',
      commune: 'تقرت',
      customerType: 'wholesaler',
      creditLimit: 1200000,
      paymentTermsDays: 45,
      totalInvoiced: 1600000,
      totalPaid: 1100000,
      outstandingBalance: 500000,
      overdueBalance: 200000,
      oldestDueDate: daysAgo(20),
      lastPaymentDate: daysAgo(35),
      riskScore: 58,
      riskLevel: 'medium',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'تحويلات بنكية مباشرة مع بنك BNA',
      createdAt: daysAgo(210),
      updatedAt: daysAgo(5),
    },
    {
      id: 'cust-14',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-014',
      name: 'نور الدين بلخير',
      companyName: 'سوف مارت للتوزيع',
      phone: '0665 12 34 89',
      whatsapp: '0665 12 34 89',
      address: 'حي تكسبت',
      wilaya: 'الوادي',
      commune: 'الوادي',
      customerType: 'retailer',
      creditLimit: 500000,
      paymentTermsDays: 30,
      totalInvoiced: 690000,
      totalPaid: 610000,
      outstandingBalance: 80000,
      overdueBalance: 0,
      oldestDueDate: daysAhead(7),
      lastPaymentDate: daysAgo(12),
      riskScore: 18,
      riskLevel: 'low',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'سداد منتظم جداً',
      createdAt: daysAgo(175),
      updatedAt: daysAgo(12),
    },
    {
      id: 'cust-15',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-015',
      name: 'مراد بوعبد الله',
      companyName: 'التيطري للمشروبات والعصائر',
      phone: '0773 89 01 23',
      whatsapp: '0773 89 01 23',
      address: 'حي المصلى',
      wilaya: 'المدية',
      commune: 'المدية',
      customerType: 'wholesaler',
      creditLimit: 750000,
      paymentTermsDays: 30,
      totalInvoiced: 980000,
      totalPaid: 680000,
      outstandingBalance: 300000,
      overdueBalance: 170000,
      oldestDueDate: daysAgo(15),
      lastPaymentDate: daysAgo(26),
      riskScore: 52,
      riskLevel: 'medium',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'يسدد عادة شطرين كل شهر',
      createdAt: daysAgo(105),
      updatedAt: daysAgo(4),
    },
    {
      id: 'cust-16',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-016',
      name: 'عبد النور بلقاسمي',
      companyName: 'مؤسسة متيجة للتوزيع السريع',
      phone: '0556 34 56 78',
      whatsapp: '0556 34 56 78',
      address: 'المنطقة الصناعية أولاد يعيش',
      wilaya: 'البليدة',
      commune: 'أولاد يعيش',
      customerType: 'distributor',
      creditLimit: 1500000,
      paymentTermsDays: 45,
      totalInvoiced: 2200000,
      totalPaid: 1400000,
      outstandingBalance: 800000,
      overdueBalance: 500000,
      oldestDueDate: daysAgo(33),
      lastPaymentDate: daysAgo(40),
      riskScore: 74,
      riskLevel: 'high',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'رصيد كبير متأخر، تم الاتفاق على جدول دفع أسبوعي',
      createdAt: daysAgo(240),
      updatedAt: daysAgo(2),
    },
    {
      id: 'cust-17',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-017',
      name: 'طارق مزيان',
      companyName: 'ميزاب للمواد الغذائية العامة',
      phone: '0667 90 12 34',
      whatsapp: '0667 90 12 34',
      address: 'شارع الشيخ بيوض',
      wilaya: 'غرداية',
      commune: 'القرارة',
      customerType: 'retailer',
      creditLimit: 400000,
      paymentTermsDays: 30,
      totalInvoiced: 510000,
      totalPaid: 450000,
      outstandingBalance: 60000,
      overdueBalance: 0,
      oldestDueDate: daysAhead(18),
      lastPaymentDate: daysAgo(14),
      riskScore: 12,
      riskLevel: 'low',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'انضباط كامل في مواعيد الدفع',
      createdAt: daysAgo(85),
      updatedAt: daysAgo(14),
    },
    {
      id: 'cust-18',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-018',
      name: 'توفيق بلحاج',
      companyName: 'بلحاج لقطع الغيار والميكانيك',
      phone: '0775 23 45 67',
      whatsapp: '0775 23 45 67',
      address: 'حي الكرامة',
      wilaya: 'مستغانم',
      commune: 'مستغانم',
      customerType: 'company',
      creditLimit: 900000,
      paymentTermsDays: 30,
      totalInvoiced: 1150000,
      totalPaid: 800000,
      outstandingBalance: 350000,
      overdueBalance: 240000,
      oldestDueDate: daysAgo(24),
      lastPaymentDate: daysAgo(38),
      riskScore: 66,
      riskLevel: 'high',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'يحتاج اتصال لتثبيت استلام الدفعة القادمة',
      createdAt: daysAgo(190),
      updatedAt: daysAgo(3),
    },
    {
      id: 'cust-19',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-019',
      name: 'عبد العزيز سعدي',
      companyName: 'سعدي وتوشي للتوزيع',
      phone: '0558 76 54 32',
      whatsapp: '0558 76 54 32',
      address: 'حي 20 أوت',
      wilaya: 'سكيكدة',
      commune: 'سكيكدة',
      customerType: 'wholesaler',
      creditLimit: 850000,
      paymentTermsDays: 30,
      totalInvoiced: 1020000,
      totalPaid: 950000,
      outstandingBalance: 70000,
      overdueBalance: 0,
      oldestDueDate: daysAhead(5),
      lastPaymentDate: daysAgo(16),
      riskScore: 22,
      riskLevel: 'low',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'يسدد عبر حساب CCP',
      createdAt: daysAgo(115),
      updatedAt: daysAgo(16),
    },
    {
      id: 'cust-20',
      organizationId: orgId,
      accountNumber: 'CUST-DZ-020',
      name: 'إبراهيم بن عيسى',
      companyName: 'بن عيسى هايبرماركت',
      phone: '0669 01 23 45',
      whatsapp: '0669 01 23 45',
      address: 'طريق تيزي وزو',
      wilaya: 'بومرداس',
      commune: 'بومرداس',
      customerType: 'retailer',
      creditLimit: 600000,
      paymentTermsDays: 30,
      totalInvoiced: 780000,
      totalPaid: 420000,
      outstandingBalance: 360000,
      overdueBalance: 210000,
      oldestDueDate: daysAgo(21),
      lastPaymentDate: daysAgo(30),
      riskScore: 64,
      riskLevel: 'high',
      assignedCollectorId: 'user-03',
      assignedCollectorName: 'كريم براهيمي',
      notes: 'أكد السداد نهاية الأسبوع الحالي، يجب تأكيد الموعد',
      createdAt: daysAgo(135),
      updatedAt: daysAgo(2),
    },
  ];

  const invoices: Invoice[] = [
    // cust-01 (Mohamed Belkacem)
    {
      id: 'inv-001',
      organizationId: orgId,
      customerId: 'cust-01',
      customerName: 'محمد بلقاسم',
      customerPhone: '0550 45 89 12',
      invoiceNumber: 'INV-2026-001',
      issueDate: daysAgo(65),
      dueDate: daysAgo(35),
      items: [
        { id: 'item-1', description: 'زيت المائدة 5 لتر (كرتون 4 وحدات)', quantity: 50, unitPrice: 3200, totalPrice: 160000 },
        { id: 'item-2', description: 'سكر أبيض 25 كغ (أكياس)', quantity: 20, unitPrice: 2200, totalPrice: 44000 },
      ],
      subtotal: 204000,
      discount: 0,
      tax: 0,
      total: 204000,
      paidAmount: 84000,
      remainingAmount: 120000,
      status: 'overdue',
      daysOverdue: 35,
      createdAt: daysAgo(65),
    },
    {
      id: 'inv-002',
      organizationId: orgId,
      customerId: 'cust-01',
      customerName: 'محمد بلقاسم',
      customerPhone: '0550 45 89 12',
      invoiceNumber: 'INV-2026-015',
      issueDate: daysAgo(45),
      dueDate: daysAgo(15),
      items: [
        { id: 'item-3', description: 'معجون طماطم 800غ (كرتون 24 علبة)', quantity: 40, unitPrice: 4000, totalPrice: 160000 },
      ],
      subtotal: 160000,
      discount: 0,
      tax: 0,
      total: 160000,
      paidAmount: 0,
      remainingAmount: 160000,
      status: 'overdue',
      daysOverdue: 15,
      createdAt: daysAgo(45),
    },
    {
      id: 'inv-003',
      organizationId: orgId,
      customerId: 'cust-01',
      customerName: 'محمد بلقاسم',
      customerPhone: '0550 45 89 12',
      invoiceNumber: 'INV-2026-028',
      issueDate: daysAgo(15),
      dueDate: daysAhead(15),
      items: [
        { id: 'item-4', description: 'حليب معقم 1 لتر (كرتون 12 علبة)', quantity: 80, unitPrice: 1500, totalPrice: 120000 },
      ],
      subtotal: 120000,
      discount: 0,
      tax: 0,
      total: 120000,
      paidAmount: 0,
      remainingAmount: 120000,
      status: 'issued',
      daysOverdue: 0,
      createdAt: daysAgo(15),
    },

    // cust-02 (Abdelkader Maouche - High Risk!)
    {
      id: 'inv-004',
      organizationId: orgId,
      customerId: 'cust-02',
      customerName: 'عبد القادر معوش',
      customerPhone: '0661 78 23 45',
      invoiceNumber: 'INV-2026-004',
      issueDate: daysAgo(93),
      dueDate: daysAgo(48),
      items: [
        { id: 'item-5', description: 'إسمنت بورتلاندي 50 كغ (شحنة 10 طن)', quantity: 200, unitPrice: 1750, totalPrice: 350000 },
      ],
      subtotal: 350000,
      discount: 0,
      tax: 0,
      total: 350000,
      paidAmount: 0,
      remainingAmount: 350000,
      status: 'overdue',
      daysOverdue: 48,
      createdAt: daysAgo(93),
    },
    {
      id: 'inv-005',
      organizationId: orgId,
      customerId: 'cust-02',
      customerName: 'عبد القادر معوش',
      customerPhone: '0661 78 23 45',
      invoiceNumber: 'INV-2026-018',
      issueDate: daysAgo(75),
      dueDate: daysAgo(30),
      items: [
        { id: 'item-6', description: 'حديد تسليح 12 مم (حزمة)', quantity: 2, unitPrice: 100000, totalPrice: 200000 },
      ],
      subtotal: 200000,
      discount: 0,
      tax: 0,
      total: 200000,
      paidAmount: 0,
      remainingAmount: 200000,
      status: 'overdue',
      daysOverdue: 30,
      createdAt: daysAgo(75),
    },

    // cust-05 (Béchir Othmani - 180,000 DZD - overdue 27 days - The Golden Widget item!)
    {
      id: 'inv-006',
      organizationId: orgId,
      customerId: 'cust-05',
      customerName: 'بشير عثماني',
      customerPhone: '0662 33 11 88',
      invoiceNumber: 'INV-2026-021',
      issueDate: daysAgo(42),
      dueDate: daysAgo(27),
      items: [
        { id: 'item-7', description: 'أرز بسمتي فاخر 5 كغ (كرتون)', quantity: 30, unitPrice: 3000, totalPrice: 90000 },
        { id: 'item-8', description: 'كسكسي متوسط 1 كغ (صندوق 10 كغ)', quantity: 45, unitPrice: 2000, totalPrice: 90000 },
      ],
      subtotal: 180000,
      discount: 0,
      tax: 0,
      total: 180000,
      paidAmount: 0,
      remainingAmount: 180000,
      status: 'overdue',
      daysOverdue: 27,
      notes: 'فاتورة تسليم باتنة - أجل 15 يوم',
      createdAt: daysAgo(42),
    },

    // cust-07 (Fawzi Derradji)
    {
      id: 'inv-007',
      organizationId: orgId,
      customerId: 'cust-07',
      customerName: 'فوزي دراجي',
      customerPhone: '0561 22 77 99',
      invoiceNumber: 'INV-2026-012',
      issueDate: daysAgo(82),
      dueDate: daysAgo(22),
      items: [
        { id: 'item-9', description: 'تجهيزات مخزن ورفوف حديدية صناعية', quantity: 1, unitPrice: 450000, totalPrice: 450000 },
      ],
      subtotal: 450000,
      discount: 0,
      tax: 0,
      total: 450000,
      paidAmount: 0,
      remainingAmount: 450000,
      status: 'overdue',
      daysOverdue: 22,
      createdAt: daysAgo(82),
    },
    {
      id: 'inv-008',
      organizationId: orgId,
      customerId: 'cust-07',
      customerName: 'فوزي دراجي',
      customerPhone: '0561 22 77 99',
      invoiceNumber: 'INV-2026-033',
      issueDate: daysAgo(20),
      dueDate: daysAhead(40),
      items: [
        { id: 'item-10', description: 'عربات نقل بضائع ومستلزمات تفريغ', quantity: 5, unitPrice: 70000, totalPrice: 350000 },
      ],
      subtotal: 350000,
      discount: 0,
      tax: 0,
      total: 350000,
      paidAmount: 0,
      remainingAmount: 350000,
      status: 'issued',
      daysOverdue: 0,
      createdAt: daysAgo(20),
    },

    // cust-09 (Ali Cherif)
    {
      id: 'inv-009',
      organizationId: orgId,
      customerId: 'cust-09',
      customerName: 'علي شريف',
      customerPhone: '0770 99 44 22',
      invoiceNumber: 'INV-2026-009',
      issueDate: daysAgo(62),
      dueDate: daysAgo(42),
      items: [
        { id: 'item-11', description: 'عطور ومستحضرات تجميل مستوردة', quantity: 50, unitPrice: 4400, totalPrice: 220000 },
      ],
      subtotal: 220000,
      discount: 0,
      tax: 0,
      total: 220000,
      paidAmount: 0,
      remainingAmount: 220000,
      status: 'overdue',
      daysOverdue: 42,
      createdAt: daysAgo(62),
    },

    // cust-04 (Hicham Taheri)
    {
      id: 'inv-010',
      organizationId: orgId,
      customerId: 'cust-04',
      customerName: 'هشام طاهري',
      customerPhone: '0555 98 43 21',
      invoiceNumber: 'INV-2026-019',
      issueDate: daysAgo(48),
      dueDate: daysAgo(18),
      items: [
        { id: 'item-12', description: 'شواحن وكوابل وإكسسوارات هواتف أصلية', quantity: 100, unitPrice: 1900, totalPrice: 190000 },
      ],
      subtotal: 190000,
      discount: 0,
      tax: 0,
      total: 190000,
      paidAmount: 0,
      remainingAmount: 190000,
      status: 'overdue',
      daysOverdue: 18,
      createdAt: daysAgo(48),
    },
    {
      id: 'inv-011',
      organizationId: orgId,
      customerId: 'cust-04',
      customerName: 'هشام طاهري',
      customerPhone: '0555 98 43 21',
      invoiceNumber: 'INV-2026-035',
      issueDate: daysAgo(10),
      dueDate: daysAhead(20),
      items: [
        { id: 'item-13', description: 'سماعات بلوتوث ولاسلكية', quantity: 80, unitPrice: 2000, totalPrice: 160000 },
      ],
      subtotal: 160000,
      discount: 0,
      tax: 0,
      total: 160000,
      paidAmount: 0,
      remainingAmount: 160000,
      status: 'issued',
      daysOverdue: 0,
      createdAt: daysAgo(10),
    },

    // cust-12 (Abdelhak Ghanem)
    {
      id: 'inv-012',
      organizationId: orgId,
      customerId: 'cust-12',
      customerName: 'عبد الحق غانم',
      customerPhone: '0771 66 33 22',
      invoiceNumber: 'INV-2026-010',
      issueDate: daysAgo(58),
      dueDate: daysAgo(38),
      items: [
        { id: 'item-14', description: 'مشروبات غازية وعصائر (منصات متنوعة)', quantity: 150, unitPrice: 1733.33, totalPrice: 260000 },
      ],
      subtotal: 260000,
      discount: 0,
      tax: 0,
      total: 260000,
      paidAmount: 0,
      remainingAmount: 260000,
      status: 'overdue',
      daysOverdue: 38,
      createdAt: daysAgo(58),
    },

    // cust-16 (Abdennour Belkasmi)
    {
      id: 'inv-013',
      organizationId: orgId,
      customerId: 'cust-16',
      customerName: 'عبد النور بلقاسمي',
      customerPhone: '0556 34 56 78',
      invoiceNumber: 'INV-2026-007',
      issueDate: daysAgo(78),
      dueDate: daysAgo(33),
      items: [
        { id: 'item-15', description: 'شحنة مواد تنظيف ومطهرات بالجملة', quantity: 250, unitPrice: 2000, totalPrice: 500000 },
      ],
      subtotal: 500000,
      discount: 0,
      tax: 0,
      total: 500000,
      paidAmount: 0,
      remainingAmount: 500000,
      status: 'overdue',
      daysOverdue: 33,
      createdAt: daysAgo(78),
    },

    // cust-18 (Toufik Belhadj)
    {
      id: 'inv-014',
      organizationId: orgId,
      customerId: 'cust-18',
      customerName: 'توفيق بلحاج',
      customerPhone: '0775 23 45 67',
      invoiceNumber: 'INV-2026-017',
      issueDate: daysAgo(54),
      dueDate: daysAgo(24),
      items: [
        { id: 'item-16', description: 'فلاتر وزيوت سيارات اصطناعية', quantity: 40, unitPrice: 6000, totalPrice: 240000 },
      ],
      subtotal: 240000,
      discount: 0,
      tax: 0,
      total: 240000,
      paidAmount: 0,
      remainingAmount: 240000,
      status: 'overdue',
      daysOverdue: 24,
      createdAt: daysAgo(54),
    },

    // cust-20 (Ibrahim Ben Aissa)
    {
      id: 'inv-015',
      organizationId: orgId,
      customerId: 'cust-20',
      customerName: 'إبراهيم بن عيسى',
      customerPhone: '0669 01 23 45',
      invoiceNumber: 'INV-2026-020',
      issueDate: daysAgo(51),
      dueDate: daysAgo(21),
      items: [
        { id: 'item-17', description: 'عجائن غذائية وكسكسي متنوع', quantity: 70, unitPrice: 3000, totalPrice: 210000 },
      ],
      subtotal: 210000,
      discount: 0,
      tax: 0,
      total: 210000,
      paidAmount: 0,
      remainingAmount: 210000,
      status: 'overdue',
      daysOverdue: 21,
      createdAt: daysAgo(51),
    },
  ];

  const payments: Payment[] = [
    {
      id: 'pay-001',
      organizationId: orgId,
      customerId: 'cust-01',
      customerName: 'محمد بلقاسم',
      receiptNumber: 'REC-2026-001',
      paymentDate: daysAgo(40),
      amount: 84000,
      paymentMethod: 'cash',
      referenceNumber: 'وصل كاش #102',
      collectedById: 'user-03',
      collectedByName: 'كريم براهيمي',
      notes: 'تسديد جزئي نقداً عند زيارة المحل',
      allocations: [{ invoiceId: 'inv-001', invoiceNumber: 'INV-2026-001', amountAllocated: 84000 }],
      createdAt: daysAgo(40),
    },
    {
      id: 'pay-002',
      organizationId: orgId,
      customerId: 'cust-04',
      customerName: 'هشام طاهري',
      receiptNumber: 'REC-2026-002',
      paymentDate: daysAgo(25),
      amount: 150000,
      paymentMethod: 'edahabia',
      referenceNumber: 'RIP-CCP-449102',
      collectedById: 'user-03',
      collectedByName: 'كريم براهيمي',
      notes: 'تحويل عبر تطبيق بريدي موب',
      createdAt: daysAgo(25),
    },
    {
      id: 'pay-003',
      organizationId: orgId,
      customerId: 'cust-07',
      customerName: 'فوزي دراجي',
      receiptNumber: 'REC-2026-003',
      paymentDate: daysAgo(45),
      amount: 400000,
      paymentMethod: 'cheque',
      referenceNumber: 'شيك BNA رقم 099231',
      collectedById: 'user-02',
      collectedByName: 'سمير قادري',
      notes: 'تم صرف الشيك بالبنك الوطني الجزائري',
      createdAt: daysAgo(45),
    },
    {
      id: 'pay-004',
      organizationId: orgId,
      customerId: 'cust-06',
      customerName: 'رضا زرقين',
      receiptNumber: 'REC-2026-004',
      paymentDate: daysAgo(10),
      amount: 120000,
      paymentMethod: 'ccp',
      referenceNumber: 'وصل CCP رقم 8812',
      collectedById: 'user-03',
      collectedByName: 'كريم براهيمي',
      notes: 'تسوية منتظمة في الأجل',
      createdAt: daysAgo(10),
    },
  ];

  const ledgerEntries: LedgerEntry[] = [
    // cust-01 ledger
    {
      id: 'ledg-001',
      organizationId: orgId,
      customerId: 'cust-01',
      entryDate: daysAgo(65),
      entryType: 'invoice',
      referenceNumber: 'INV-2026-001',
      referenceId: 'inv-001',
      debit: 204000,
      credit: 0,
      runningBalance: 204000,
      description: 'فاتورة مبيعات رقم INV-2026-001',
    },
    {
      id: 'ledg-002',
      organizationId: orgId,
      customerId: 'cust-01',
      entryDate: daysAgo(45),
      entryType: 'invoice',
      referenceNumber: 'INV-2026-015',
      referenceId: 'inv-015',
      debit: 160000,
      credit: 0,
      runningBalance: 364000,
      description: 'فاتورة مبيعات رقم INV-2026-015',
    },
    {
      id: 'ledg-003',
      organizationId: orgId,
      customerId: 'cust-01',
      entryDate: daysAgo(40),
      entryType: 'payment',
      referenceNumber: 'REC-2026-001',
      referenceId: 'pay-001',
      debit: 0,
      credit: 84000,
      runningBalance: 280000,
      description: 'سداد نقداً بموجب الوصل REC-2026-001',
    },
    {
      id: 'ledg-004',
      organizationId: orgId,
      customerId: 'cust-01',
      entryDate: daysAgo(15),
      entryType: 'invoice',
      referenceNumber: 'INV-2026-028',
      referenceId: 'inv-028',
      debit: 120000,
      credit: 0,
      runningBalance: 400000,
      description: 'فاتورة مبيعات رقم INV-2026-028',
    },

    // cust-05 ledger (Béchir Othmani)
    {
      id: 'ledg-005',
      organizationId: orgId,
      customerId: 'cust-05',
      entryDate: daysAgo(42),
      entryType: 'invoice',
      referenceNumber: 'INV-2026-021',
      referenceId: 'inv-006',
      debit: 180000,
      credit: 0,
      runningBalance: 180000,
      description: 'فاتورة مبيعات مواد غذائية رقم INV-2026-021',
    },

    // cust-02 ledger (Abdelkader Maouche)
    {
      id: 'ledg-006',
      organizationId: orgId,
      customerId: 'cust-02',
      entryDate: daysAgo(93),
      entryType: 'invoice',
      referenceNumber: 'INV-2026-004',
      referenceId: 'inv-004',
      debit: 350000,
      credit: 0,
      runningBalance: 350000,
      description: 'فاتورة مواد بناء رقم INV-2026-004',
    },
    {
      id: 'ledg-007',
      organizationId: orgId,
      customerId: 'cust-02',
      entryDate: daysAgo(75),
      entryType: 'invoice',
      referenceNumber: 'INV-2026-018',
      referenceId: 'inv-005',
      debit: 200000,
      credit: 0,
      runningBalance: 550000,
      description: 'فاتورة حديد تسليح رقم INV-2026-018',
    },
  ];

  const collectionTasks: CollectionTask[] = [
    {
      id: 'task-001',
      organizationId: orgId,
      customerId: 'cust-05',
      customerName: 'بشير عثماني',
      customerPhone: '0662 33 11 88',
      companyName: 'محلات الأوراس للمواد الغذائية',
      assignedToId: 'user-03',
      assignedToName: 'كريم براهيمي',
      title: 'اتصال ومتابعة الفاتورة المتأخرة 180,000 دج',
      description: 'متأخر 27 يوماً - طلب التحصيل أو تأكيد موعد زيارة المندوب',
      targetAmount: 180000,
      priority: 'urgent',
      dueDate: daysAhead(0), // Due Today!
      status: 'pending',
      daysOverdue: 27,
      createdAt: daysAgo(2),
    },
    {
      id: 'task-002',
      organizationId: orgId,
      customerId: 'cust-02',
      customerName: 'عبد القادر معوش',
      customerPhone: '0661 78 23 45',
      companyName: 'مؤسسة معوش لمواد البناء',
      assignedToId: 'user-03',
      assignedToName: 'كريم براهيمي',
      title: 'متابعة وعد دفع منقوض (Broken Promise)',
      description: 'تعهد بالدفع يوم 28 الماضي ولم يسدد، الاتصال للإنذار قبل تعليق الحساب',
      targetAmount: 550000,
      priority: 'urgent',
      dueDate: daysAhead(0), // Due Today!
      status: 'pending',
      daysOverdue: 48,
      createdAt: daysAgo(3),
    },
    {
      id: 'task-003',
      organizationId: orgId,
      customerId: 'cust-01',
      customerName: 'محمد بلقاسم',
      customerPhone: '0550 45 89 12',
      companyName: 'سوبرماركت البركة',
      assignedToId: 'user-03',
      assignedToName: 'كريم براهيمي',
      title: 'إرسال رسالة تذكير عبر واتساب بالفاتورة الثانية',
      description: 'إرسال كشف حساب ملخص ومطالبة بتسديد الشطر الثاني',
      targetAmount: 160000,
      priority: 'high',
      dueDate: daysAhead(1),
      status: 'pending',
      daysOverdue: 15,
      createdAt: daysAgo(1),
    },
    {
      id: 'task-004',
      organizationId: orgId,
      customerId: 'cust-09',
      customerName: 'علي شريف',
      customerPhone: '0770 99 44 22',
      companyName: 'محلات شريف للعطور',
      assignedToId: 'user-03',
      assignedToName: 'كريم براهيمي',
      title: 'زيارة ميدانية لمحل الزبون بمغنية',
      description: 'الزبون لا يرد على الهاتف منذ يومين، توجيه المندوب الميداني للتحصيل',
      targetAmount: 220000,
      priority: 'urgent',
      dueDate: daysAhead(0), // Due Today!
      status: 'pending',
      daysOverdue: 42,
      createdAt: daysAgo(2),
    },
    {
      id: 'task-005',
      organizationId: orgId,
      customerId: 'cust-07',
      customerName: 'فوزي دراجي',
      customerPhone: '0561 22 77 99',
      companyName: 'مؤسسة سيرتا للتجهيزات',
      assignedToId: 'user-02',
      assignedToName: 'سمير قادري',
      title: 'مراجعة موعد الشيك الثاني',
      description: 'التواصل مع المدير المالي لشركة سيرتا لتأكيد جاهزية الرصيد البنكي',
      targetAmount: 450000,
      priority: 'medium',
      dueDate: daysAhead(3),
      status: 'in_progress',
      daysOverdue: 22,
      createdAt: daysAgo(4),
    },
  ];

  const collectionAttempts: CollectionAttempt[] = [
    {
      id: 'att-001',
      organizationId: orgId,
      customerId: 'cust-01',
      customerName: 'محمد بلقاسم',
      channel: 'phone',
      result: 'answered',
      attemptDate: daysAgo(5),
      notes: 'أكد أنه باع كمية معتبرة وسيسدد 100,000 دج الأسبوع القادم',
      memberId: 'user-03',
      memberName: 'كريم براهيمي',
      nextFollowUpDate: daysAhead(2),
    },
    {
      id: 'att-002',
      organizationId: orgId,
      customerId: 'cust-02',
      customerName: 'عبد القادر معوش',
      channel: 'phone',
      result: 'promise_to_pay',
      attemptDate: daysAgo(10),
      notes: 'وعد بتحويل 300,000 دج في 28 الشهر الماضي',
      memberId: 'user-03',
      memberName: 'كريم براهيمي',
      nextFollowUpDate: daysAgo(3),
    },
    {
      id: 'att-003',
      organizationId: orgId,
      customerId: 'cust-05',
      customerName: 'بشير عثماني',
      channel: 'whatsapp',
      result: 'answered',
      attemptDate: daysAgo(3),
      notes: 'تم إرسال كشف الفاتورة رقم INV-2026-021 وقرأ الرسالة',
      memberId: 'user-03',
      memberName: 'كريم براهيمي',
      nextFollowUpDate: daysAhead(0),
    },
    {
      id: 'att-004',
      organizationId: orgId,
      customerId: 'cust-09',
      customerName: 'علي شريف',
      channel: 'phone',
      result: 'no_answer',
      attemptDate: daysAgo(1),
      notes: 'الهاتف يرن ولا أحد يجيب',
      memberId: 'user-03',
      memberName: 'كريم براهيمي',
      nextFollowUpDate: daysAhead(0),
    },
  ];

  const promiseToPays: PromiseToPay[] = [
    {
      id: 'prom-001',
      organizationId: orgId,
      customerId: 'cust-02',
      customerName: 'عبد القادر معوش',
      customerPhone: '0661 78 23 45',
      promisedAmount: 300000,
      promisedDate: daysAgo(4), // Overdue! Broken promise!
      status: 'broken',
      isOverdue: true,
      notes: 'وعد بتحويل عبر البنك في 28 الشهر، ولم يرد إشعار التحويل',
      createdAt: daysAgo(10),
    },
    {
      id: 'prom-002',
      organizationId: orgId,
      customerId: 'cust-01',
      customerName: 'محمد بلقاسم',
      customerPhone: '0550 45 89 12',
      promisedAmount: 100000,
      promisedDate: daysAhead(2),
      status: 'pending',
      isOverdue: false,
      notes: 'وعد بدفع كاش عند مرور المندوب يوم الخميس',
      createdAt: daysAgo(5),
    },
    {
      id: 'prom-003',
      organizationId: orgId,
      customerId: 'cust-20',
      customerName: 'إبراهيم بن عيسى',
      customerPhone: '0669 01 23 45',
      promisedAmount: 210000,
      promisedDate: daysAhead(4),
      status: 'pending',
      isOverdue: false,
      notes: 'تسوية الفاتورة رقم 020 عبر بريدي موب',
      createdAt: daysAgo(2),
    },
  ];

  return {
    organization: DEMO_ORG,
    users: DEMO_USERS,
    customers,
    invoices,
    payments,
    ledgerEntries,
    collectionTasks,
    collectionAttempts,
    promiseToPays,
  };
}
